### ISSUE TITLE
unable to bootstrap orderer. Error reading genesis block file: read /var/hyperledger/orderer/orderer.genesis.block: is a directory

### ISSUE THREAD

**Issue by dlkconsultancy** [hashgraph/fabric-hcs#14]
Hi, This is the general HLF bug for 2.0.0v and your first-network example has a same bug. 
https://jira.hyperledger.org/browse/FAB-17125

Bug: Unable to bootstrap orderer - error reading genesis block file.

**Error Detail:**

panic: unable to bootstrap orderer. Error reading genesis block file: read /var/hyperledger/orderer/orderer.genesis.block: is a directory

goroutine 1 [running]:
github.com/hyperledger/fabric/orderer/common/bootstrap/file.(*fileBootstrapper).GenesisBlock(0xc00044c310, 0xc00044c310)
        /go/src/github.com/hyperledger/fabric/orderer/common/bootstrap/file/bootstrap.go:39 +0x1c0
github.com/hyperledger/fabric/orderer/common/server.extractBootstrapBlock(0xc000140d80, 0xc0003865b0)
        /go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:595 +0x13f
github.com/hyperledger/fabric/orderer/common/server.Main()
        /go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:129 +0x12c1
main.main()
        /go/src/github.com/hyperledger/fabric/cmd/orderer/main.go:15 +0x20

**Comment by wafa501** [comment]
did you found solution for this bug because i got the same
